version: "3.9"
services:
  train_yolo:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 6606:6606 # Expose Tensorboard port on host port 6606. Launch Tensorboard from within running container.
    volumes:
      - ./my/data/path/:/app/data/
      - ./my/pretrained-models/path/:/app/pretrained-models/
      - ./my/training/path/:/app/training/
      - ./my/trained-inferece-models/path/:/app/trained-inference-models/
      - ./my/test/path/:/app/test/
      - ./my/training-script/path/:/app/train_script.sh
      - ./my/validation-script/path/:/app/val_script.sh
      - ./my/yolo-model-configuration/path/:/app/yolo.yaml
    environment:
    # shell script variables
    - TRAIN_DIR=2023-02-27
    - BATCH=1
    - EPOCH=300
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    ipc: host # Allocates system GPU memory to training job
    command: /app/val_script.sh
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
