version: "3.9"
services:
  trex_pipeline_test:
    container_name: trex_pipeline_test
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
      context: .
      dockerfile: ./pipeline.x86.dockerfile
    shm_size: '2gb'
    volumes:
      - ./:/home/gadget/workspace/pipeline
      - ./untracked-data:/home/gadget/workspace/out
    command: >
      bash -c "cd pipeline && python3 ./pipeline_class.py"
