version: "3.9"
services:
  generate_trt_x86:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./path_to_validation_data:/app/images
      - ./trained-inference-models/:/app/trained-inference-models/
      - ./validation/:/app/validation/
    environment:
      - MODEL_PATH=/app/trained-inference-models/2023-03-29
      - IM_W=960
      - IM_H=640
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    command: bash /repos/LMI_AI_Solutions/object_detectors/yolov5/trt/x86/build_engine.sh
