version: "3.9"
services:
  generate_trt_x86:
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - ../data/test_640x992:/app/images # validation data (optional)
      - ../trained-inference-models/:/app/trained-inference-models/
      - ../validation/:/app/validation/  # validation output
    environment:
      - MODEL_PATH=/app/trained-inference-models/2023-07-11
      - IM_W=640
      - IM_H=992
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    command: bash /repos/LMI_AI_Solutions/object_detectors/yolov5_lmi/trt/x86/build_engine.sh
