version: "3.9"
services:
  generate_yolo_trt_arm:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./path_to_validation_data:/app/images
      - ./trained-inference-models/:/app/trained-inference-models/
      - ./validation/:/app/validation/
    environment:
      - MODEL_PATH=/app/trained-inference-models/2023-04-04
      - IM_W=640
      - IM_H=256
    runtime: nvidia
    command: bash /repos/LMI_AI_Solutions/object_detectors/yolov5/trt/arm/build_engine.sh
    