version: "3.9"
services:
  debug-lmi:
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - ./data/:/app/data/
      - ./unit_test.py:/app/unit_test.py
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    ipc: host
    command: bash -c "
      source LMI_AI_Solutions/lmi_ai.env
      && python3 /app/unit_test.py"
    # stdin_open: true # docker run -i
    # tty: true        # docker run -i
