version: "3.9"
services:
  anomalib_train:
    build:
      context: .
      dockerfile: ./dockerfile.x86_64
    volumes:
      - ./path_to_my_data/train/:/app/data/train/
      - ./path_to_my_config_files/:/app/configs/
      - ./path_to_my_data/test/:/app/data/test
      - ./path_to_my_engine_files/:/app/engine
      - ./path_to_onnx_files/:/app/onnx
      - ./path_to_my_output_files/:/app/out
    environment:
      - model=padim
    shm_size: '20gb' 
    # runtime: nvidia # For Jetson 
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    # command: python3 -O anomalib/tools/train.py --config /app/configs/$model.yaml
    # command: /app/LMI_AI_SOLUTIONS/anomaly_detectors/anomalib_lmi/anomaly_model.py convert $model /app/onnx /app/engine

