version: "3.9"
services:
  generate_trt:
    build:
      context: .
      dockerfile: ./dockerfile.$PLATFORM
    volumes:
      - $WEIGHT_PATH:/app/best.pt
      - ${WEIGHT_PATH}_out/:/app/trt_engines/
      - ./build_engine.sh:/app/build_engine.sh
    env_file:
      - ./.env
    shm_size: '2gb'
    runtime: nvidia
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    command: bash /app/build_engine.sh
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
